services:
  query-builder-app:
    build:
      context: ./query-builder-app
      dockerfile: Dockerfile
    ports:
      - "443:3000" # Port 80 as this will be the public facing port
    depends_on:
      - query-builder-backend
    env_file:
      - ./query-builder-app/.env.production
    restart: unless-stopped

  query-builder-backend:
    build:
      context: ./query-builder-backend
      dockerfile: Dockerfile
    ports:
    - "3000:55555"
    depends_on:
    - redis
    env_file:
      - ./query-builder-backend/.env
    restart: unless-stopped

  redis:
    image: redis:latest
    restart: unless-stopped