name: App Test
on:
    pull_request:
    push:
        branches:
            - dev
            - main
        paths:
            - 'query-builder-app/**'
jobs:
    test:
        runs-on: ubuntu-latest
        defaults:
           run:
             working-directory: ./query-builder-app/
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                version: '9.1.2'
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                cache: 'pnpm'
                cache-dependency-path: './query-builder-app/pnpm-lock.yaml'
            - name: Install Dependencies
              run: pnpm install --frozen-lockfile
            - name: Test
              run: pnpm test
              working-directory: query-builder-app
