name: App Lint
on:
    push:
        branches:
            - dev
            - main
        paths:
            - 'query-builder-app/**'
jobs:
    lint:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Install pnpm
              uses: pnpm/action-setup@v4
              with:
                version: '9.1.2'
            - name: Setup Node.js
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'pnpm'
                cache-dependency-path: query-builder-app/pnpm-lock.yaml
            - name: Install Dependencies
              run: pnpm install --frozen-lockfile
            - name: Lint
              run: pnpm lint
              working-directory: query-builder-app