name: Build Test
on:
    workflow_dispatch:
    pull_request:
        branches:
            - main
            - dev
        paths:
            - 'query-builder-app/**'
            - 'query-builder-backend/**'

jobs:
    app-build:
        runs-on: ubuntu-latest
        steps:
            - name: App Checkout
              uses: actions/checkout@v4
            - name: App Install pnpm
              uses: pnpm/action-setup@v4
              with:
                version: '9.1.2'
            - name: App Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'pnpm'
                cache-dependency-path: query-builder-app/pnpm-lock.yaml
            - name: App Install Dependencies
              run: |
                pnpm install --frozen-lockfile
              working-directory: query-builder-app
            - name: App Make env file
              run: |
                touch .env
                echo NEXT_PUBLIC_SUPABASE_URL = ${{ env.SUPABASE_URL }} >> .env
                echo NEXT_PUBLIC_SUPABASE_ANON_KEY = ${{ env.SUPABASE_ANON_KEY }} >> .env
                echo NEXT_PUBLIC_SUPABASE_PROJECT_ID = ${{ env.SUPABASE_SERVICE_ROLE_KEY}} >> .env
                cat .env
              working-directory: query-builder-app
            - name: App Build
              run: |
                pnpm run build
              working-directory: query-builder-app
    backend-build:
        runs-on: ubuntu-latest
        steps: 
            - name: Backend Checkout
              uses: actions/checkout@v4
            - name: App Install pnpm
              uses: pnpm/action-setup@v4
              with:
                version: '9.1.2'
            - name: Backend Setup Node
              uses: actions/setup-node@v4
              with:
                node-version: 20
                cache: 'pnpm'
                cache-dependency-path: query-builder-backend/pnpm-lock.yaml
            - name: Backend Install Dependencies
              run: |
                pnpm install --frozen-lockfile
              working-directory: query-builder-backend
            - name: Make env file
              run: |
                touch .env
                echo SUPABASE_URL = ${{ env.SUPABASE_URL }} >> .env
                echo SUPABASE_KEY = ${{ env.SUPABASE_ANON_KEY }} >> .env
                echo SUPABASE_SERVICE_KEY = ${{ env.SUPABASE_SERVICE_ROLE_KEY}} >> .env
                echo SUPABASE_JWT_SECRET = ${{ env.SUPABASE_JWT_SECRET }} >> .env
                cat .env
              working-directory: query-builder-backend
            - name: Backend Build
              run: |
                pnpm run build
              working-directory: query-builder-backend